import { app, BrowserWindow } from "electron";
import { ipcMain } from "electron";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 700,
        width: 900,
        minHeight: 600,
        minWidth: 450,
        useContentSize: true,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    mainWindow.webContents.openDevTools();
    mainWindow.setMinimumSize(600, 650);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Handle IPC requests from renderer process
ipcMain.handle("get-weather-data", async (event, latitude: number, longitude: number) => {
    return await fetchWeather(latitude, longitude);
});

ipcMain.handle("get-location-data", async (event, cityName: string) => {
    //return await fetchGeoLocationData("tokyo");

    return await fetchGeoLocationData(cityName);
});
ipcMain.handle("get-default-location", async () => {
    return await getDefaultLocation();
});

ipcMain.on("set-default-location", (event, newDefaultCity: IGeoCoordinatesData) => {
    setDefaultLocation(newDefaultCity);
});

import path from "path";
import dotenv from "dotenv";
import { IWeatherData, IWeatherAPIResponse, IGeoAPIResponse, IGeoCoordinatesData } from "./typings";

let weatherDataCache: { data: IWeatherData | null; timeStamp: number } = {
    data: null,
    timeStamp: 0,
};

let geoCoordinatesCache = {
    latitude: 0,
    longitude: 0,
};

let defaultLoc: IGeoCoordinatesData = {
    city: "Toronto",
    adminRegion: "Ontario",
    country: "Canada",
    latitude: 43.70643,
    longitude: -79.39864,
};

const CACHE_DURATION = 30 * 60 * 1000;

const envPath = configureAPIKeys();
dotenv.config({ path: envPath });
const weatherAPIKey = process.env.WEATHER_API as string;
const weatherAPIKeyLatitudeParameter = process.env.WEATHER_API_LATITUDE_PARAMETER as string;
const weatherAPIKeyLongitudeParameter = process.env.WEATHER_API_LONGITUDE_PARAMETER as string;
const weatherAPIKeyForecastParameters = process.env.WEATHER_API_FORECAST_PARAMETERS as string;
const geoAPIKey = process.env.GEO_API as string;
const geoAPIKeyParameters = process.env.GEO_API_PARAMETERS as string;

async function fetchWeather(latitude: number, longitude: number): Promise<IWeatherAPIResponse> {
    try {
        if (
            weatherDataCache.data == null ||
            Date.now() - weatherDataCache.timeStamp > CACHE_DURATION ||
            (geoCoordinatesCache.latitude !== latitude &&
                geoCoordinatesCache.longitude !== longitude)
        ) {
            console.log("fresh api pull");
            // console.log(Date.now() - weatherDataCache.timeStamp);
            const configuredWeatherAPIKey: string = `${weatherAPIKey}${weatherAPIKeyLatitudeParameter}${latitude}${weatherAPIKeyLongitudeParameter}${longitude}${weatherAPIKeyForecastParameters}`;

            const response = await fetch(configuredWeatherAPIKey);

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const data = await response.json();

            let weatherData: IWeatherData = {
                isDay: data.current.is_day == 1 ? true : false,
                utcOffSetSeconds: data.utc_offset_seconds,
                units: {
                    temperature: data.daily_units.apparent_temperature_max,
                    precipitation: data.daily_units.precipitation_probability_max,
                },
                currentApparentTemp: data.current.apparent_temperature,
                currentTemp: data.current.temperature_2m,
                currentWeatherCode: data.current.weather_code,
                forecastDays: data.daily.time,
                weatherCode: data.daily.weather_code,
                dailyMaxTemp: data.daily.temperature_2m_max,
                dailyMinTemp: data.daily.temperature_2m_min,
                dailyMaxApparentTemp: data.daily.apparent_temperature_max,
                dailyMinApparentTemp: data.daily.apparent_temperature_min,
                precipitationChance: data.daily.precipitation_probability_max,
            };
            geoCoordinatesCache = { latitude: latitude, longitude: longitude };
            weatherDataCache.data = weatherData;
            weatherDataCache.timeStamp = Date.now();
            let apiResponse: IWeatherAPIResponse = {
                status: true,
                weatherData: weatherData,
                message: "success, connection made",
            };
            console.log(apiResponse);
            return apiResponse;
        } else {
            console.log("cached weather data");
            console.log(weatherDataCache);
            let apiResponse: IWeatherAPIResponse = {
                status: true,
                weatherData: weatherDataCache.data,
                message: "success, connection made",
            };
            return apiResponse;
        }
    } catch (error) {
        console.error("Error fetching data: ", error);
        let apiResponse: IWeatherAPIResponse = {
            status: false,
            weatherData: null,
            message: `error retrieving weather data, ${error}`,
        };
        return apiResponse;
    }
}
async function fetchGeoLocationData(cityName: string): Promise<IGeoAPIResponse | null> {
    try {
        if (cityName.length > 2) {
            const configuredGeoAPIKey = `${geoAPIKey}${cityName}${geoAPIKeyParameters}`;

            const response = await fetch(configuredGeoAPIKey);
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const geoData = await response.json();
            const locationData: IGeoCoordinatesData[] = geoData.results.map((data: any) => {
                let locationData: IGeoCoordinatesData = {
                    city: data.name,
                    adminRegion: data.admin1,
                    country: data.country,
                    longitude: data.longitude,
                    latitude: data.latitude,
                };
                return locationData;
            });
            let apiResponse: IGeoAPIResponse = {
                locations: locationData,
            };
            return apiResponse;
        } else {
            return null;
        }
    } catch (error) {
        console.log("Error fetching data: ", error);
        return null;
    }
}

async function getDefaultLocation(): Promise<IGeoCoordinatesData> {
    //change it to read from a file later and will need await later

    return defaultLoc;
}
function setDefaultLocation(newDefault: IGeoCoordinatesData) {
    //code here for setting the newDefaultCity
    console.log(newDefault);
    defaultLoc = newDefault;
}

function configureAPIKeys() {
    if (!app.isPackaged) {
        return path.join(process.cwd(), ".env");
    } else {
        return path.join(process.resourcesPath, ".env");
    }
}
